--INSERTAR REGIONES

--------------------------------------------------------
--  DDL for Table NUEVOSHORIZONTES_REGION
--------------------------------------------------------

  CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_REGION" 
   (	"ID_REGION" NUMBER(11,0), 
	"NOMBRE_REGION" NVARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_REGION
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('1','Tarapacá');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('2','Antofagasta');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('3','Atacama');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('4','Coquimbo');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('5','Valparaíso');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('6','O Higgins');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('7','Maule');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('8','Bío-bío');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('9','La Araucanía');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('10','Los Lagos');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('11','Aysén');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('12','Magallanes');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('13','Metropolitana');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('14','Los Ríos');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('15','Arica');
Insert into C##NOVO.NUEVOSHORIZONTES_REGION (ID_REGION,NOMBRE_REGION) values ('16','Ñuble');
--------------------------------------------------------
--  DDL for Index SYS_C008901
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C008901" ON "C##NOVO"."NUEVOSHORIZONTES_REGION" ("ID_REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_REGION
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_REGION" MODIFY ("ID_REGION" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_REGION" ADD PRIMARY KEY ("ID_REGION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;



--INSERTA COMUNAS
--------------------------------------------------------
--  DDL for Table NUEVOSHORIZONTES_COMUNA
--------------------------------------------------------

  CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_COMUNA" 
   (	"ID_COMUNA" NUMBER(11,0), 
	"NOMBRE_COMUNA" NVARCHAR2(15), 
	"REGION_COMUNA_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_COMUNA
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('2101','Antofagasta','2');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('1101','Iquique','1');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('2201','Calama','2');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('3101','Copiapó','3');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('3301','Vallenar','3');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('4101','La Serena','4');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('4102','Coquimbo','4');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('4301','Ovalle','4');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('5101','Valparaíso','5');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('5103','Concón','5');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('5109','Viña del Mar','5');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('5301','Los Andes','5');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('5601','San Antonio','5');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('6115','Rengo','6');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('6103','Rancagua','6');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('7101','Talca','7');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('7301','Curicó','7');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('7401','Linares','7');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('16101','Chillán','16');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('8101','Concepción','8');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('8102','Coronel','8');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('9201','Angol','9');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('14101','Valdivia','14');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('10101','Puerto Montt','10');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('10201','Castro','10');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('11101','Coyhaique','11');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('12101','Punta Arenas','12');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13101','Santiago','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13104','Conchalí','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13107','Huechuraba','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13114','Las Condes','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13118','Macul','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13110','La Florida','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13120','Ñuñoa','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13124','Providencia','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13123','Providencia','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13125','Quilicura','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13127','Recoleta','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13130','San Miguel','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13132','Vitacura','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13301','Colina','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13401','San Bernardo','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13402','Buin','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13601','Talagante','13');
Insert into C##NOVO.NUEVOSHORIZONTES_COMUNA (ID_COMUNA,NOMBRE_COMUNA,REGION_COMUNA_ID) values ('13122','Peñalolén','13');
--------------------------------------------------------
--  DDL for Index SYS_C0010017
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C0010017" ON "C##NOVO"."NUEVOSHORIZONTES_COMUNA" ("ID_COMUNA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NUEVOSHORI_REGION_COM_AFB42872
--------------------------------------------------------

  CREATE INDEX "C##NOVO"."NUEVOSHORI_REGION_COM_AFB42872" ON "C##NOVO"."NUEVOSHORIZONTES_COMUNA" ("REGION_COMUNA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_COMUNA
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_COMUNA" MODIFY ("REGION_COMUNA_ID" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_COMUNA" MODIFY ("ID_COMUNA" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_COMUNA" ADD PRIMARY KEY ("ID_COMUNA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NUEVOSHORIZONTES_COMUNA
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_COMUNA" ADD CONSTRAINT "NUEVOSHOR_REGION_CO_AFB42872_F" FOREIGN KEY ("REGION_COMUNA_ID")
	  REFERENCES "C##NOVO"."NUEVOSHORIZONTES_REGION" ("ID_REGION") DEFERRABLE INITIALLY DEFERRED ENABLE;




--INSERTAR SEDES
--------------------------------------------------------
--  DDL for Table NUEVOSHORIZONTES_SEDE
--------------------------------------------------------

  CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_SEDE" 
   (	"ID_SEDE" NUMBER(11,0), 
	"NOMBRE_SEDE" NVARCHAR2(15), 
	"DIRECCION_SEDE" NVARCHAR2(25), 
	"TELEFONO_SEDE" NUMBER(11,0), 
	"COMUNA_SEDE_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_SEDE
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_SEDE (ID_SEDE,NOMBRE_SEDE,DIRECCION_SEDE,TELEFONO_SEDE, FOTOSEDE,COMUNA_SEDE_ID) values ('1','NH Conchalí','Diego Silva Henríquez 179','212341230', 'sedes/colegio1.jpg','13104');
Insert into C##NOVO.NUEVOSHORIZONTES_SEDE (ID_SEDE,NOMBRE_SEDE,DIRECCION_SEDE,TELEFONO_SEDE, FOTOSEDE,COMUNA_SEDE_ID) values ('2','NH Vitacura','Las Hualtatas 7440','212341231', 'sedes/colegio2.jpg','13132');
Insert into C##NOVO.NUEVOSHORIZONTES_SEDE (ID_SEDE,NOMBRE_SEDE,DIRECCION_SEDE,TELEFONO_SEDE, FOTOSEDE,COMUNA_SEDE_ID) values ('3','NH Peñalolén','Valle del Aconcagua 8031','212341232', 'sedes/colegio3.jpg','13122');
--------------------------------------------------------
--  DDL for Index SYS_C008910
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C008910" ON "C##NOVO"."NUEVOSHORIZONTES_SEDE" ("ID_SEDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NUEVOSHORI_COMUNA_SED_606D7FDE
--------------------------------------------------------

  CREATE INDEX "C##NOVO"."NUEVOSHORI_COMUNA_SED_606D7FDE" ON "C##NOVO"."NUEVOSHORIZONTES_SEDE" ("COMUNA_SEDE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_SEDE
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SEDE" MODIFY ("ID_SEDE" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SEDE" MODIFY ("TELEFONO_SEDE" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SEDE" MODIFY ("COMUNA_SEDE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SEDE" ADD PRIMARY KEY ("ID_SEDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NUEVOSHORIZONTES_SEDE
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SEDE" ADD CONSTRAINT "NUEVOSHOR_COMUNA_SE_606D7FDE_F" FOREIGN KEY ("COMUNA_SEDE_ID")
	  REFERENCES "C##NOVO"."NUEVOSHORIZONTES_COMUNA" ("ID_COMUNA") DEFERRABLE INITIALLY DEFERRED ENABLE;




--INSERTAR MATERIAS 
--------------------------------------------------------
--  DDL for Table NUEVOSHORIZONTES_MATERIA
--------------------------------------------------------

  CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_MATERIA" 
   (	"ID_MATERIA" NVARCHAR2(6), 
	"NOMBRE_MATERIA" NVARCHAR2(25)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_MATERIA
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('ART','Artes Visuales');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('NAT','Ciencias Naturales');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('EDF','Educación Física');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('HIS','Historia y Geografía');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('ING','Inglés');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('MUS','Música');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('REL','Religión');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('TEC','Tecnología');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('BIO','Biología');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('QUI','Química');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('FIS','Física');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('FIL','Filosofía');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('LEN','Lenguaje y Comunicación');
Insert into C##NOVO.NUEVOSHORIZONTES_MATERIA (ID_MATERIA,NOMBRE_MATERIA) values ('Mat','Matemáticas');
--------------------------------------------------------
--  DDL for Index SYS_C0010021
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C0010021" ON "C##NOVO"."NUEVOSHORIZONTES_MATERIA" ("ID_MATERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_MATERIA
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_MATERIA" MODIFY ("ID_MATERIA" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_MATERIA" ADD PRIMARY KEY ("ID_MATERIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;



--INSERTAR APODERADO
 CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_APODERADO" 
   (	"RUT_APODERADO" NVARCHAR2(12), 
	"NOMBRE_APODERADO" NVARCHAR2(15), 
	"APPATERNO_APODERADO" NVARCHAR2(30), 
	"APMATERNO_APODERADO" NVARCHAR2(30), 
	"DIRECCION_APODERADO" NVARCHAR2(30), 
	"TELEFONO_APODERADO" NUMBER(11,0), 
	"CORREO_APODERADO" NVARCHAR2(30), 
	"PASSWORD" NVARCHAR2(125)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_APODERADO
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('14999968-K','Lola','Alaniz','Quezada','Isabel Arriaga # 345','938537063','loalqu@nh.cl','loalqu');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('15.719.431-3','Camila','Roa','Saldaña','Nicole Mora # 1432','91978256','carosa@nh.cl','carosa');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('16498556-3','Pablo','Nava','Murillo','Daniela Aguirre # 6184','90498372','panamu@nh.cl','panamu');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('17332091-4','Ivanna','Quintanilla','Soto','Emily Solís # 2397','999463067','ivquso@nh.cl','ivquso');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('2075286-6','Amaya','León','Jurado','Av. Alejandro Alicea # 759','972770466','amleju@nh.cl','amleju');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('13160589-7','Rodrigo','Reyes','Guerra','Urb. Abigail Madrigal # 21841','918927190','roregu@nh.cl','roregu');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('17412246-6','Noelia','Rivera','Busquets','Av. Clara Benavides # 9506','976108576','noribu@nh.cl','noribu');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('16695101-1','Andrea','Clara','Mora','Av. Alejandro Nazario # 3662','1473491','anclmo@nh.cl','anclmo');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('15135011-9','Francisco','Oquendo','Castro','Urb. Ivan Ordóñez # 8 Piso 77','959000132','froqca@nh.cl','froqca');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('14443571-0','Alessandra','Tovar','Donoso','Mariangel Saldivar # 84 Dp','991692509','altodo@nh.cl','altodo');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('13408685-8','Alan','Delgado','Villareal','Av. Julieta Vargas # 6','993804300','aldevi@nh.cl','aldevi');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('18336409-K','Miguel','Matos','Espino','Av. Ximena Cortés # 9 Hab. 474','1213898','mimaes@nh.cl','mimaes');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('20035939-9','Irene','Salgado','Davis','Urb. Felipe Macías # 04','986597919','irsada@nh.cl','irsada');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('12.78943-9','Jerónimo','Arellano','Apodaca','Malena Rivas # 12515','923643536','jearap@nh.cl','jearap');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('15261000-9','Alejandra','Rendón','Fuentes','Dante Estévez # 1011','970010441','alrefu@nh.cl','alrefu');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('15266073-1','Rafael','Treviño','Ortiz','Josefina Cardenas # 35','91987762','ratror@nh.cl','ratror');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('15334777-8','Samanta','Saldivar','Zamora','Sophie Guillen # 1','933139912','sasaza@nh.cl','sasaza');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('15379090-6','Fabiana','Duarte','Calderón','Av. Hidalgo Vélez # 7721','948170739','faduca@nh.cl','faduca');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('16828780-1','Josefa','Meza','Cepeda','Pablo Muñoz # 7598','975492647','jomece@nh.cl','jomece');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('17154993-0','Jimena','Gaytán','Fonseca','Av. Valery Villagómez # 19688','91358064','jigafo@nh.cl','jigafo');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('17196526-8','Kevin','Frías','Rangel','Lucas Alva # 74139','80846856','kefrra@nh.cl','kefrra');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('17623178-5','Vicente','De La Cruz','Medrano','Sophie Carrion # 9','1687213','videme@nh.cl','videme');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('18031129-7','Lautaro','Holguín','De La Rosa','Hugo Pedroza # 10','1919205','lahode@nh.cl','lahode');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('13109183-4','Natalia','Alaniz','Leiva','Bianca Colón # 5158','991776614','naalle@nh.cl','naalle');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('13174189-8','Ariana','Corral','Zamudio','Miguel Ángel Garrido # 9','956179380','arcoza@nh.cl','arcoza');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('14309712-9','Gabriel','Robledo','Tijerina','Dante Arevalo # 737','9566262','garoti@nh.cl','garoti');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('14393043-2','Zoe','Ureña','Salas','Josefina Marroquín # 042','91656518','zoursa@nh.cl','zoursa');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('14681405-0','Joshua','Del Río','Galván','Carla Ríos # 840','931032607','jodega@nh.cl','jodega');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('11724002-9','Julián','Zapata','Mejía','Anthony Ramos # 323','91329669','juzame@nh.cl','juzame');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('15152267-K','Francisco','Fierro','Olave','Benjamín Armijo # 589','91914115','frfiol@nh.cl','frfiol');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('15802192-7','Olivia','Rosado','Dueñas','Catalina Moreno # 6846','948138943','olrodu@nh.cl','olrodu');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('15885423-6','Adriana','Campos','Padilla','Daniela Beltrán # 3','942601125','adcapa@nh.cl','adcapa');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('16133707-2','Ricardo','Cabán','Roldán','Ana Benavídez # 87','91639437','ricaro@nh.cl','ricaro');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('16172996-5','Agustina','Muñoz','Rojas','Jazmín Hernández # 123','91292791','agmuro@nh.cl','agmuro');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('16338098-6','Amelia','Porras','Guevara','Alejandro Quintero # 10','91175312','ampogu@nh.cl','ampogu');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('17020482-4','Gabriela','Samaniego','Cavazos','Pablo Terán # 53','916588660','gasaca@nh.cl','gasaca');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('17278434-8','Micaela','Nazario','Riojas','Luciana Araña # 789','949336730','minari@nh.cl','minari');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('17471263-8','Ian','Cabán','Puente','Josué León # 81 Piso 5','991156564','iacapu@nh.cl','iacapu');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('17740223-0','Malena','Sanches','Vallejo','Camila Téllez # 7845','91668480','masava@nh.cl','masava');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('17932470-9','Ornela','Escobedo','Benítez','Gael Urrutia # 1668','937097274','oresbe@nh.cl','oresbe');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('18069249-5','Josué','Gallardo','Rosas','Alan Sáenz # 7','941721078','jogaro@nh.cl','jogaro');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('18329329-K','Esteban','Collado','Mora','Ana Cardenas # 7836','97580059','escomo@nh.cl','escomo');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('18567277-8','Fernanda','Burgos','Escobar','Nahuel Casares # 1 Hab. 51','91341755','febues@nh.cl','febues');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('14358987-0','Aarón','Suárez','Juárez','Alan Castro # 39455 Piso 3','9380134','aasuju@nh.cl','aasuju');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('13924250-5','Renata','Villa','Vela','Aitana Sanches # 1998','91505290','revive@nh.cl','revive');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('10439076-5','Manuel','Solano','Aranda','Valentino Arredondo # 429','948514470','masoar@nh.cl','masoar');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('10958306-5','Martina','Varela','Girón','Juan Martín Estrada # 2203','964622469','mavagi@nh.cl','mavagi');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('11890105-3','Alexa','Palomo','Navarrete','Av. Renata Farías # 403 Hab. 2','948475841','alpana@nh.cl','alpana');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('12539491-4','Diego','Solís','Prado','Violeta Lovato # 62 Piso 4','91558615','disopr@nh.cl','disopr');
Insert into C##NOVO.NUEVOSHORIZONTES_APODERADO (RUT_APODERADO,NOMBRE_APODERADO,APPATERNO_APODERADO,APMATERNO_APODERADO,DIRECCION_APODERADO,TELEFONO_APODERADO,CORREO_APODERADO,PASSWORD) values ('13183151-K','René','Razo','Estay','Sara Sofía Cantú # 29650','91460098','reraes@nh.cl','reraes');
--------------------------------------------------------
--  DDL for Index SYS_C0010010
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C0010010" ON "C##NOVO"."NUEVOSHORIZONTES_APODERADO" ("RUT_APODERADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_APODERADO
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_APODERADO" MODIFY ("RUT_APODERADO" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_APODERADO" MODIFY ("TELEFONO_APODERADO" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_APODERADO" ADD PRIMARY KEY ("RUT_APODERADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;



--INSERT TIPOS DE SALA
--------------------------------------------------------
--  DDL for Table NUEVOSHORIZONTES_TIPO_SALA
--------------------------------------------------------

  CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_TIPO_SALA" 
   (	"ID_TIPO_SALA" NUMBER(11,0), 
	"NOMBRE_TIPO_SALA" NVARCHAR2(12)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_TIPO_SALA
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_TIPO_SALA (ID_TIPO_SALA,NOMBRE_TIPO_SALA) values ('1','Sala');
Insert into C##NOVO.NUEVOSHORIZONTES_TIPO_SALA (ID_TIPO_SALA,NOMBRE_TIPO_SALA) values ('2','Laboratorio');
Insert into C##NOVO.NUEVOSHORIZONTES_TIPO_SALA (ID_TIPO_SALA,NOMBRE_TIPO_SALA) values ('3','Gimnasio');
Insert into C##NOVO.NUEVOSHORIZONTES_TIPO_SALA (ID_TIPO_SALA,NOMBRE_TIPO_SALA) values ('4','Auditorio');
Insert into C##NOVO.NUEVOSHORIZONTES_TIPO_SALA (ID_TIPO_SALA,NOMBRE_TIPO_SALA) values ('5','Oficina');
Insert into C##NOVO.NUEVOSHORIZONTES_TIPO_SALA (ID_TIPO_SALA,NOMBRE_TIPO_SALA) values ('6','Biblioteca');
--------------------------------------------------------
--  DDL for Index SYS_C0010030
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C0010030" ON "C##NOVO"."NUEVOSHORIZONTES_TIPO_SALA" ("ID_TIPO_SALA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_TIPO_SALA
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_TIPO_SALA" MODIFY ("ID_TIPO_SALA" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_TIPO_SALA" ADD PRIMARY KEY ("ID_TIPO_SALA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;



--INSERTAR SALAS
--------------------------------------------------------
--  DDL for Table NUEVOSHORIZONTES_SALA
--------------------------------------------------------

  CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_SALA" 
   (	"ID_SALA" NUMBER(11,0), 
	"NOMBRE_SALA" NVARCHAR2(10), 
	"SEDE_SALA_ID" NUMBER(11,0), 
	"TIPO_SALA_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_SALA
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('1','A001','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('2','A002','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('3','A003','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('4','A004','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('5','A005','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('6','A006','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('7','A007','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('8','A008','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('9','A009','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('10','A010','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('11','A011','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('12','A012','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('13','A013','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('14','A014','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('15','A015','1','1');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('20','L001','1','2');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('21','L002','1','2');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('22','L003','1','2');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('30','G001','1','3');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('31','G002','1','3');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('40','AUD01','1','4');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('50','OF001','1','5');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('51','OF002','1','5');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('52','OF003','1','5');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('53','OF004','1','5');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('54','OF005','1','5');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('90','B001','1','6');
Insert into C##NOVO.NUEVOSHORIZONTES_SALA (ID_SALA,NOMBRE_SALA,SEDE_SALA_ID,TIPO_SALA_ID) values ('91','B002','1','6');
--------------------------------------------------------
--  DDL for Index SYS_C0010038
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C0010038" ON "C##NOVO"."NUEVOSHORIZONTES_SALA" ("ID_SALA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NUEVOSHORI_SEDE_SALA__5C0F13A4
--------------------------------------------------------

  CREATE INDEX "C##NOVO"."NUEVOSHORI_SEDE_SALA__5C0F13A4" ON "C##NOVO"."NUEVOSHORIZONTES_SALA" ("SEDE_SALA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NUEVOSHORI_TIPO_SALA__C6C3CDF4
--------------------------------------------------------

  CREATE INDEX "C##NOVO"."NUEVOSHORI_TIPO_SALA__C6C3CDF4" ON "C##NOVO"."NUEVOSHORIZONTES_SALA" ("TIPO_SALA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_SALA
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SALA" MODIFY ("SEDE_SALA_ID" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SALA" MODIFY ("TIPO_SALA_ID" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SALA" ADD PRIMARY KEY ("ID_SALA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SALA" MODIFY ("ID_SALA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NUEVOSHORIZONTES_SALA
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SALA" ADD CONSTRAINT "NUEVOSHOR_SEDE_SALA_5C0F13A4_F" FOREIGN KEY ("SEDE_SALA_ID")
	  REFERENCES "C##NOVO"."NUEVOSHORIZONTES_SEDE" ("ID_SEDE") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_SALA" ADD CONSTRAINT "NUEVOSHOR_TIPO_SALA_C6C3CDF4_F" FOREIGN KEY ("TIPO_SALA_ID")
	  REFERENCES "C##NOVO"."NUEVOSHORIZONTES_TIPO_SALA" ("ID_TIPO_SALA") DEFERRABLE INITIALLY DEFERRED ENABLE;


--INSERTAR ALUMNOS



--INSERTAR DOCENTES
--------------------------------------------------------
--  DDL for Table NUEVOSHORIZONTES_DOCENTE
--------------------------------------------------------

  CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE" 
   (	"RUT_DOCENTE" NVARCHAR2(12), 
	"NOMBRE_DOCENTE" NVARCHAR2(15), 
	"APPATERNO_DOCENTE" NVARCHAR2(30), 
	"APMATERNO_DOCENTE" NVARCHAR2(30), 
	"DIRECCION_DOCENTE" NVARCHAR2(30), 
	"TELEFONO_DOCENTE" NUMBER(11,0), 
	"CORREO_DOCENTE" NVARCHAR2(30), 
	"PASSWORD" NVARCHAR2(125), 
	"SEDE_DOCENTE_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_DOCENTE
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('10885023-K','Emilia','Barrios','Cantú','Valentino Carrero # 43513','9911430436','embaca@nh.cl','embaca','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('13907753-9','Matthew','Nahuel','Acuña','Av. Paula Fajardo # 36','991894863','manaac@nh.cl','manaac','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('12508971-2','Fernando','Briones','Uribe','Josefina Iglesias # 77','925408050','februr@nh.cl','februr','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('9.031.629-k','Alica Anastasia','Perez','Lopez','Las Flores 2810','56945977628','aliciapl@nh.cl','aliciapl','2');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('14932342-2','Ariana','Perea','Uribe','Micaela Olivas # 1 Piso 7','911691873','arpemi@nh.cl','arpemi','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('14131966-3','Antonia','Montaño','Santana','Av. María Paula García # 6','911094860','anmosa@nh.cl','anmosa','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('20.446.061-2','Diego Pablo','Romero','Gomez','Julia Bernstein 630','56979877309','diegorg@nh.cl','diegorg','2');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('19.254.021-2','Juan Pablo','Zuñiga','Arancibia','Los laureles 3495','56979874562','juanza@nh.cl','juanza','2');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('9.831.363-k','Maria Luisa','Godoy','Cruz','Las tertulias 2389','56948516459','mariagc@nh.cl','mariagc','2');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('18.341.219-k','Leopoldo','Gonzalez','Muñoz','Aurora 8952','5697','leopoldogm@nh.cl','leopoldogm','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('17.808.732.1','Cristian','Espinoza','Ruiz','Rosario Norte 407','915469873','cresru@nh.cl','cresru','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('13.204.281-2','Luis Felipe','Rodriguez','Parraguez','La abadia 5021','56978587486','luisrp@nh.cl','luisrp','2');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('10.241.491-6','Javier','Rojo','Barahona','Padre hurtado 513','56982546978','javierrb@nh.cl','javierrb','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('5.635.363-9','Juan Ignacio','Cortez','Muñoz','Las Vizcachas 365','5699785864','juancm@nh.cl','juancm','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('21.751.274-8','Aaron','Piper','Guiterrez','Madrid 392','5697854369','aaronpg@nh.cl','aaronpg','3');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('15.407.381-9','Francisco','Pizarro','Echeverrie','Avenida vitacura 291','56932112356','franciscope@nh.cl','franciscope','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('19.999.777-k','Jeremy Camilo','Fuentealba','Ermosilla','Los leones 014','56966658916','jeremyfe@nh.cl','jeremyfe','2');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('18.547.985-3','Alfonso','Castellon','Ezeta','Puente Alto 989','56984572136','alcaez@nh.cl','alcaez','2');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('17.684.254-7','Fernanda','Gomez','Ruiz','San pablo 346','56987546324','fegoru@nh.cl','fegoru','3');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('20.722.541-K','Angelo','Barahona','Bravo','Estacion Huasco 0229','56954896344','ababr@nh.cl','ababr','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('20.287.177-1','Juan Ignacio','Muñoz','Fuentes','Avenida Pedro Fontova 8076','56978456955','juanmf@nh.cl','juanmf','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('15.758.566-9','Alan','Brito','Jorquera','Jorge Nitales 382','56979854396','alanbj@nh.cl','alannbj','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('19.021.221-4','Gelido','Geloso','Glacido','Glaicar 392','56989566598','gelidogg@nh.cl','gelidogg','3');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('16.291.192-4','Caleido','Escopio','Alacopa','Michigan 39212-D','56978542365','caleidoea@nh.cl','caleidoea','3');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('14.256.324-5','Felipe','Parra','Parra','Parral 392103','56987969586','felipepp@nh.cl','felipepp','2');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('12.382.482-2','Javiera','Peral','Peralta','Pescal 019','56979858692','javierapp@nh.cl','javierapp','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('12.343.291-2','Azul','Silverster','Estalone','Las liebres 102','56987362598','azulse@nh.cl','azulse','1');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('15.436.771-7','Faviola','Romero','Gomez','Marauka 193','56978457810','faviolarg@nh.cl','faviolarg','3');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('7.321.638.-3','Richar','Rojas','Remo','Los libertadores 3492','56956859863','richarrr@nh.cl','richarr','3');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('8.656.936-9','Carlos','Nuñez','Soto Soto','Sotero 3','56933633336','carlosns@nh.cl','carlosns','3');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE (RUT_DOCENTE,NOMBRE_DOCENTE,APPATERNO_DOCENTE,APMATERNO_DOCENTE,DIRECCION_DOCENTE,TELEFONO_DOCENTE,CORREO_DOCENTE,PASSWORD,SEDE_DOCENTE_ID) values ('3.434.121-k','Edolfo','Ibañez','Del Campo','Irarrazabal 2392','56933414785','eid@nh.cl','eid','3');
--------------------------------------------------------
--  DDL for Index NUEVOSHORI_SEDE_DOCEN_1CE8F79A
--------------------------------------------------------

  CREATE INDEX "C##NOVO"."NUEVOSHORI_SEDE_DOCEN_1CE8F79A" ON "C##NOVO"."NUEVOSHORIZONTES_DOCENTE" ("SEDE_DOCENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010051
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C0010051" ON "C##NOVO"."NUEVOSHORIZONTES_DOCENTE" ("RUT_DOCENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_DOCENTE
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE" MODIFY ("RUT_DOCENTE" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE" MODIFY ("TELEFONO_DOCENTE" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE" MODIFY ("SEDE_DOCENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE" ADD PRIMARY KEY ("RUT_DOCENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NUEVOSHORIZONTES_DOCENTE
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE" ADD CONSTRAINT "NUEVOSHOR_SEDE_DOCE_1CE8F79A_F" FOREIGN KEY ("SEDE_DOCENTE_ID")
	  REFERENCES "C##NOVO"."NUEVOSHORIZONTES_SEDE" ("ID_SEDE") DEFERRABLE INITIALLY DEFERRED ENABLE;



--INSERTAR ASIGNATURAS
--------------------------------------------------------
--  DDL for Table NUEVOSHORIZONTES_ASIGNATURA
--------------------------------------------------------

  CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_ASIGNATURA" 
   (	"ID_ASIGNATURA" NVARCHAR2(6), 
	"NOMBRE_MATERIA_ID" NVARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('FIS001','FIS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('CN001','NAT');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('FIS002','FIS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('FIS003','FIS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('CN002','NAT');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('FIS004','FIS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('CN003','NAT');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('ART001','ART');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('ART002','ART');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('ART003','ART');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('HIS001','HIS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('HIS002','HIS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('HIS003','HIS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('HIS004','HIS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('EF001','EDF');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('EF002','EDF');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('EF004','EDF');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('EF003','EDF');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('ING001','ING');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('ING002','ING');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('ING003','ART');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('ING004','ING');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('MUS001','MUS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('MUS002','MUS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('MUS003','MUS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('MUS004','MUS');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('REL001','REL');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('REL002','REL');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('TEC001','TEC');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('TEC002','TEC');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('TEC003','TEC');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('TEC004','TEC');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('BIO001','BIO');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('BIO002','BIO');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('BIO003','BIO');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('BIO004','BIO');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('QUI001','QUI');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('QUI002','QUI');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('QUI003','QUI');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('QUI004','QUI');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('FIL001','FIL');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('FIL002','FIL');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('FIL003','FIL');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('FIL004','FIL');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('LEN001','LEN');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('LEN002','LEN');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('LEN003','LEN');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('LEN004','LEN');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('MAT001','Mat');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('MAT002','Mat');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('MAT003','Mat');
Insert into C##NOVO.NUEVOSHORIZONTES_ASIGNATURA (ID_ASIGNATURA,NOMBRE_MATERIA_ID) values ('MAT004','Mat');
--------------------------------------------------------
--  DDL for Index SYS_C0010012
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C0010012" ON "C##NOVO"."NUEVOSHORIZONTES_ASIGNATURA" ("ID_ASIGNATURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NUEVOSHORI_NOMBRE_MAT_ED7DDB8A
--------------------------------------------------------

  CREATE INDEX "C##NOVO"."NUEVOSHORI_NOMBRE_MAT_ED7DDB8A" ON "C##NOVO"."NUEVOSHORIZONTES_ASIGNATURA" ("NOMBRE_MATERIA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_ASIGNATURA
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_ASIGNATURA" MODIFY ("NOMBRE_MATERIA_ID" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_ASIGNATURA" MODIFY ("ID_ASIGNATURA" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_ASIGNATURA" ADD PRIMARY KEY ("ID_ASIGNATURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NUEVOSHORIZONTES_ASIGNATURA
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_ASIGNATURA" ADD CONSTRAINT "NUEVOSHOR_NOMBRE_MA_ED7DDB8A_F" FOREIGN KEY ("NOMBRE_MATERIA_ID")
	  REFERENCES "C##NOVO"."NUEVOSHORIZONTES_MATERIA" ("ID_MATERIA") DEFERRABLE INITIALLY DEFERRED ENABLE;


--INSERTAR CURSOS
--------------------------------------------------------
--  DDL for Table NUEVOSHORIZONTES_CURSO
--------------------------------------------------------

  CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_CURSO" 
   (	"ID_CURSO" NUMBER(11,0), 
	"NOMBRE_CURSO" NVARCHAR2(30), 
	"DOCENTE_CURSO_ID" NVARCHAR2(12)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_CURSO
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_CURSO (ID_CURSO,NOMBRE_CURSO,DOCENTE_CURSO_ID) values ('1201','IV A','12508971-2');
Insert into C##NOVO.NUEVOSHORIZONTES_CURSO (ID_CURSO,NOMBRE_CURSO,DOCENTE_CURSO_ID) values ('1202','IV B','10885023-K');
Insert into C##NOVO.NUEVOSHORIZONTES_CURSO (ID_CURSO,NOMBRE_CURSO,DOCENTE_CURSO_ID) values ('1203','IV C','13907753-9');
Insert into C##NOVO.NUEVOSHORIZONTES_CURSO (ID_CURSO,NOMBRE_CURSO,DOCENTE_CURSO_ID) values ('1204','IV D','14932342-2');
--------------------------------------------------------
--  DDL for Index SYS_C0010019
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C0010019" ON "C##NOVO"."NUEVOSHORIZONTES_CURSO" ("ID_CURSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NUEVOSHORI_DOCENTE_CU_B35AA1BD
--------------------------------------------------------

  CREATE INDEX "C##NOVO"."NUEVOSHORI_DOCENTE_CU_B35AA1BD" ON "C##NOVO"."NUEVOSHORIZONTES_CURSO" ("DOCENTE_CURSO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_CURSO
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_CURSO" MODIFY ("DOCENTE_CURSO_ID" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_CURSO" MODIFY ("ID_CURSO" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_CURSO" ADD PRIMARY KEY ("ID_CURSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NUEVOSHORIZONTES_CURSO
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_CURSO" ADD CONSTRAINT "NUEVOSHOR_DOCENTE_C_B35AA1BD_F" FOREIGN KEY ("DOCENTE_CURSO_ID")
	  REFERENCES "C##NOVO"."NUEVOSHORIZONTES_DOCENTE" ("RUT_DOCENTE") DEFERRABLE INITIALLY DEFERRED ENABLE;
--INSERTAR HORARIOS

--INSERTAR BLOQUES

--INSERTAR BOLETAS

--INSERTAR TIPOS DE PAGOS

--INSERTAR PAGOS

--INSERTAR NOTICIAS

--INSERTAR ADMINISTRADOR

--INSERTAR MUCHOAMUCHOS DOCENTE ASIGNATURAS
--------------------------------------------------------
--  DDL for Table NUEVOSHORIZONTES_DOCENTE_A1F07
--------------------------------------------------------

  CREATE TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" 
   (	"ID" NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DOCENTE_ID" NVARCHAR2(12), 
	"ASIGNATURA_ID" NVARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07
SET DEFINE OFF;
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('1','10885023-K','FIS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('2','10885023-K','FIS003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('3','10885023-K','CN001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('15','13907753-9','FIL002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('16','13907753-9','HIS002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('17','13907753-9','HIS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('7','12508971-2','MAT002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('8','12508971-2','MAT001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('9','12508971-2','MAT004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('10','12508971-2','MAT003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('33','9.031.629-k','FIS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('34','9.031.629-k','HIS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('35','9.031.629-k','MUS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('36','9.831.363-k','ART001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('18','13907753-9','FIL001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('19','14932342-2','ING004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('20','14932342-2','HIS003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('21','14932342-2','HIS004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('22','14932342-2','ING003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('23','14131966-3','LEN002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('24','14131966-3','LEN004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('25','14131966-3','LEN001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('26','14131966-3','LEN003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('27','20.446.061-2','FIS004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('28','20.446.061-2','QUI001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('29','20.446.061-2','ING001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('30','19.254.021-2','ART001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('31','19.254.021-2','EF001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('32','19.254.021-2','HIS004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('37','9.831.363-k','MUS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('38','9.831.363-k','ING001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('39','18.341.219-k','ART001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('40','18.341.219-k','MUS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('41','18.341.219-k','ING001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('42','17.808.732.1','HIS002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('43','17.808.732.1','HIS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('44','17.808.732.1','HIS003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('45','13.204.281-2','MAT001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('46','13.204.281-2','LEN001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('47','13.204.281-2','FIS002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('48','10.241.491-6','LEN002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('49','10.241.491-6','MAT001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('50','10.241.491-6','FIL001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('51','5.635.363-9','ART001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('52','5.635.363-9','REL001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('53','5.635.363-9','TEC002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('54','21.751.274-8','CN003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('55','21.751.274-8','CN001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('56','21.751.274-8','FIS003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('57','15.407.381-9','MAT001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('58','15.407.381-9','FIL001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('59','19.999.777-k','EF001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('60','19.999.777-k','MUS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('61','18.547.985-3','MAT001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('62','18.547.985-3','MAT002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('63','18.547.985-3','MAT003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('64','17.684.254-7','FIS004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('65','17.684.254-7','CN003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('66','17.684.254-7','CN001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('67','20.722.541-K','EF001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('68','20.722.541-K','EF004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('69','20.722.541-K','EF002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('70','20.287.177-1','FIS004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('71','20.287.177-1','CN002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('72','20.287.177-1','FIS003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('73','15.758.566-9','ART001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('74','15.758.566-9','CN003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('75','15.758.566-9','FIS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('76','19.021.221-4','HIS004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('77','19.021.221-4','ING001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('78','19.021.221-4','EF002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('79','16.291.192-4','FIS004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('80','16.291.192-4','MAT001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('81','16.291.192-4','MAT002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('82','16.291.192-4','CN002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('83','14.256.324-5','ART002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('84','14.256.324-5','CN002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('85','14.256.324-5','FIS002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('86','12.382.482-2','FIS004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('87','12.382.482-2','ART002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('88','12.382.482-2','CN001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('89','12.343.291-2','ING004');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('90','12.343.291-2','ING001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('91','12.343.291-2','EF003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('92','15.436.771-7','ART001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('93','15.436.771-7','FIS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('94','15.436.771-7','EF003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('95','7.321.638.-3','ART001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('96','7.321.638.-3','HIS002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('97','7.321.638.-3','EF001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('98','8.656.936-9','EF001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('99','8.656.936-9','HIS002');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('100','8.656.936-9','CN001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('101','3.434.121-k','CN003');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('102','3.434.121-k','FIS001');
Insert into C##NOVO.NUEVOSHORIZONTES_DOCENTE_A1F07 (ID,DOCENTE_ID,ASIGNATURA_ID) values ('103','3.434.121-k','EF002');
--------------------------------------------------------
--  DDL for Index NUEVOSHOR_DOCENTE_I_1D70D623_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."NUEVOSHOR_DOCENTE_I_1D70D623_U" ON "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" ("DOCENTE_ID", "ASIGNATURA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NUEVOSHORI_DOCENTE_ID_59B8EDD3
--------------------------------------------------------

  CREATE INDEX "C##NOVO"."NUEVOSHORI_DOCENTE_ID_59B8EDD3" ON "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" ("DOCENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NUEVOSHORI_ASIGNATURA_B76AA4DB
--------------------------------------------------------

  CREATE INDEX "C##NOVO"."NUEVOSHORI_ASIGNATURA_B76AA4DB" ON "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" ("ASIGNATURA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010055
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NOVO"."SYS_C0010055" ON "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NUEVOSHORIZONTES_DOCENTE_A1F07
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" MODIFY ("DOCENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" MODIFY ("ASIGNATURA_ID" NOT NULL ENABLE);
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" ADD CONSTRAINT "NUEVOSHOR_DOCENTE_I_1D70D623_U" UNIQUE ("DOCENTE_ID", "ASIGNATURA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NUEVOSHORIZONTES_DOCENTE_A1F07
--------------------------------------------------------

  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" ADD CONSTRAINT "NUEVOSHOR_DOCENTE_I_59B8EDD3_F" FOREIGN KEY ("DOCENTE_ID")
	  REFERENCES "C##NOVO"."NUEVOSHORIZONTES_DOCENTE" ("RUT_DOCENTE") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "C##NOVO"."NUEVOSHORIZONTES_DOCENTE_A1F07" ADD CONSTRAINT "NUEVOSHOR_ASIGNATUR_B76AA4DB_F" FOREIGN KEY ("ASIGNATURA_ID")
	  REFERENCES "C##NOVO"."NUEVOSHORIZONTES_ASIGNATURA" ("ID_ASIGNATURA") DEFERRABLE INITIALLY DEFERRED ENABLE;
