# Generated by Django 4.1.3 on 2023-05-17 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('rut_apoderado', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('id_apoderado', models.CharField(max_length=15)),
                ('nombre_apoderado', models.CharField(max_length=15)),
                ('appaterno_apoderado', models.CharField(max_length=15)),
                ('apmaterno_apoderado', models.CharField(max_length=15)),
                ('direccion_apoderado', models.CharField(max_length=30)),
                ('telefono_apoderado', models.IntegerField()),
                ('correo_apoderado', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.IntegerField(primary_key=True, serialize=False)),
                ('apoderado_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.apoderado')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('anno_curso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Pago',
            fields=[
                ('id_tipo_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_pago', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Sala',
            fields=[
                ('id_tipo_sala', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_sala', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=15)),
                ('direccion_sede', models.CharField(max_length=25)),
                ('telefono_sede', models.IntegerField()),
                ('comuna_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.comuna')),
                ('region_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.region')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sala', models.CharField(max_length=6)),
                ('sede_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.sede')),
                ('tipo_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.tipo_sala')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('monto_pago', models.IntegerField()),
                ('boleta_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.boleta')),
                ('tipo_pago_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.tipo_pago')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.IntegerField(primary_key=True, serialize=False)),
                ('dia_horario', models.CharField(max_length=9)),
                ('curso_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('rut_docente', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('id_docente', models.CharField(max_length=15)),
                ('nombre_docente', models.CharField(max_length=15)),
                ('appaterno_docente', models.CharField(max_length=15)),
                ('apmaterno_docente', models.CharField(max_length=15)),
                ('direccion_docente', models.CharField(max_length=30)),
                ('telefono_docente', models.IntegerField()),
                ('correo_docente', models.CharField(max_length=25)),
                ('sede_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.sede')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.docente'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.region'),
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id_bloque', models.IntegerField(primary_key=True, serialize=False)),
                ('asignatura_bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.asignatura')),
                ('horario_bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.horario')),
                ('sala_bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.sala')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='curso_asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.curso'),
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut_alumno', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('id_alumno', models.CharField(max_length=15)),
                ('nombre_alumno', models.CharField(max_length=15)),
                ('appaterno_alumno', models.CharField(max_length=15)),
                ('apmaterno_alumno', models.CharField(max_length=15)),
                ('direccion_alumno', models.CharField(max_length=30)),
                ('telefono_alumno', models.IntegerField()),
                ('correo_alumno', models.CharField(max_length=25)),
                ('apoderado_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.apoderado')),
                ('curso_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.curso')),
                ('sede_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoshorizontes.sede')),
            ],
        ),
    ]
