# Generated by Django 4.1.3 on 2023-05-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoshorizontes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='region_sede',
        ),
    ]
