# Generated by Django 4.2 on 2023-06-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoshorizontes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='direccion_sede',
            field=models.CharField(max_length=40, verbose_name='Dirección de la sede'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre_sede',
            field=models.CharField(max_length=40, verbose_name='Nombre de la sede'),
        ),
    ]
