# Generated by Django 4.2 on 2023-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoshorizontes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.CharField(max_length=50, verbose_name='Correo')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('sede', models.CharField(max_length=50, verbose_name='sede')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
            ],
        ),
    ]
